### ISSUE TITLE
Twine2.munki failing because of Twine.zip changes

### ISSUE THREAD

**Issue by chelming** [autopkg/denmoff-recipes#2]
The zip downloaded from Twine no longer contains `Twine.app`, instead it contains `nw/Twine/osx64/Twine.app`. This started with Twine 2.1.

I submitted a [pull request](https://bitbucket.org/klembot/twinejs/pull-requests/134/update-scripts-packagejs/diff) on BitBucket to try and get it changed back to the way it was.

**Comment by chelming** [comment]
PR was accepted (well technically it was declined since he fixed the other packages too). I say we just wait for the next release instead of updating the recipe to look in the subfolders. Thoughts?

**Comment by denmoff** [comment]
Ah thanks for the heads up. It's been a while since i last messed with Autopkg. I'll see if there's anything i can do to fix it.

**Comment by chelming** [comment]
There's no way to recursively glob, so to fix it we'd need to use FileFinder on `nw/Twine/osx64/Twine.app`, but even then, it should be corrected with the next release of Twine and all subsequent releases. Even if we fix it for _this_ version, it'd have to be reverted for the next version.

**Comment by chelming** [comment]
Fixed! Twine was updated yesterday with the new build scripts and it's all working again.

**Comment by timsutton** [comment]
Just saw this, FYI:

https://bitbucket.org/klembot/twinejs/issues/378/importing-a-story-to-212-from-211-breaks

**Comment by chelming** [comment]
Ouch:
> So... I agree that that is as bad of an issue as can be, but I'm not sure how to go about fixing it.

**Comment by timsutton** [comment]
🤷‍♂️
